/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DashboardSubjectsRouteImport } from './routes/dashboard/subjects'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard/history'
import { Route as DashboardExamsRouteImport } from './routes/dashboard/exams'
import { Route as DashboardCertificatesRouteImport } from './routes/dashboard/certificates'
import { Route as DashboardAnnouncementsRouteImport } from './routes/dashboard/announcements'
import { Route as AdminSubjectsRouteImport } from './routes/admin/subjects'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminProgramsRouteImport } from './routes/admin/programs'
import { Route as AdminProfessorsRouteImport } from './routes/admin/professors'
import { Route as AdminGradesRouteImport } from './routes/admin/grades'
import { Route as AdminFinalExamsRouteImport } from './routes/admin/final-exams'
import { Route as AdminEnrollmentsRouteImport } from './routes/admin/enrollments'
import { Route as AdminCorrelativesRouteImport } from './routes/admin/correlatives'
import { Route as AdminCalendarRouteImport } from './routes/admin/calendar'
import { Route as AdminAttendanceRouteImport } from './routes/admin/attendance'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as AdminStudentRecordIdRouteImport } from './routes/admin/student-record.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardSubjectsRoute = DashboardSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExamsRoute = DashboardExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCertificatesRoute = DashboardCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnnouncementsRoute = DashboardAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminSubjectsRoute = AdminSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfessorsRoute = AdminProfessorsRouteImport.update({
  id: '/professors',
  path: '/professors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGradesRoute = AdminGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinalExamsRoute = AdminFinalExamsRouteImport.update({
  id: '/final-exams',
  path: '/final-exams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnrollmentsRoute = AdminEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCorrelativesRoute = AdminCorrelativesRouteImport.update({
  id: '/correlatives',
  path: '/correlatives',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentRecordIdRoute = AdminStudentRecordIdRouteImport.update({
  id: '/student-record/$id',
  path: '/student-record/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/correlatives': typeof AdminCorrelativesRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/final-exams': typeof AdminFinalExamsRoute
  '/admin/grades': typeof AdminGradesRoute
  '/admin/professors': typeof AdminProfessorsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/exams': typeof DashboardExamsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/subjects': typeof DashboardSubjectsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/student-record/$id': typeof AdminStudentRecordIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/correlatives': typeof AdminCorrelativesRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/final-exams': typeof AdminFinalExamsRoute
  '/admin/grades': typeof AdminGradesRoute
  '/admin/professors': typeof AdminProfessorsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/exams': typeof DashboardExamsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/subjects': typeof DashboardSubjectsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/student-record/$id': typeof AdminStudentRecordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/correlatives': typeof AdminCorrelativesRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/final-exams': typeof AdminFinalExamsRoute
  '/admin/grades': typeof AdminGradesRoute
  '/admin/professors': typeof AdminProfessorsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/exams': typeof DashboardExamsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/subjects': typeof DashboardSubjectsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/student-record/$id': typeof AdminStudentRecordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/calendar'
    | '/admin/correlatives'
    | '/admin/enrollments'
    | '/admin/final-exams'
    | '/admin/grades'
    | '/admin/professors'
    | '/admin/programs'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/subjects'
    | '/dashboard/announcements'
    | '/dashboard/certificates'
    | '/dashboard/exams'
    | '/dashboard/history'
    | '/dashboard/profile'
    | '/dashboard/subjects'
    | '/admin/'
    | '/dashboard/'
    | '/admin/student-record/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/calendar'
    | '/admin/correlatives'
    | '/admin/enrollments'
    | '/admin/final-exams'
    | '/admin/grades'
    | '/admin/professors'
    | '/admin/programs'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/subjects'
    | '/dashboard/announcements'
    | '/dashboard/certificates'
    | '/dashboard/exams'
    | '/dashboard/history'
    | '/dashboard/profile'
    | '/dashboard/subjects'
    | '/admin'
    | '/dashboard'
    | '/admin/student-record/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/calendar'
    | '/admin/correlatives'
    | '/admin/enrollments'
    | '/admin/final-exams'
    | '/admin/grades'
    | '/admin/professors'
    | '/admin/programs'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/subjects'
    | '/dashboard/announcements'
    | '/dashboard/certificates'
    | '/dashboard/exams'
    | '/dashboard/history'
    | '/dashboard/profile'
    | '/dashboard/subjects'
    | '/admin/'
    | '/dashboard/'
    | '/admin/student-record/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/subjects': {
      id: '/dashboard/subjects'
      path: '/subjects'
      fullPath: '/dashboard/subjects'
      preLoaderRoute: typeof DashboardSubjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/exams': {
      id: '/dashboard/exams'
      path: '/exams'
      fullPath: '/dashboard/exams'
      preLoaderRoute: typeof DashboardExamsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/certificates': {
      id: '/dashboard/certificates'
      path: '/certificates'
      fullPath: '/dashboard/certificates'
      preLoaderRoute: typeof DashboardCertificatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/announcements': {
      id: '/dashboard/announcements'
      path: '/announcements'
      fullPath: '/dashboard/announcements'
      preLoaderRoute: typeof DashboardAnnouncementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/subjects': {
      id: '/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/professors': {
      id: '/admin/professors'
      path: '/professors'
      fullPath: '/admin/professors'
      preLoaderRoute: typeof AdminProfessorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/grades': {
      id: '/admin/grades'
      path: '/grades'
      fullPath: '/admin/grades'
      preLoaderRoute: typeof AdminGradesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/final-exams': {
      id: '/admin/final-exams'
      path: '/final-exams'
      fullPath: '/admin/final-exams'
      preLoaderRoute: typeof AdminFinalExamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enrollments': {
      id: '/admin/enrollments'
      path: '/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AdminEnrollmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/correlatives': {
      id: '/admin/correlatives'
      path: '/correlatives'
      fullPath: '/admin/correlatives'
      preLoaderRoute: typeof AdminCorrelativesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/student-record/$id': {
      id: '/admin/student-record/$id'
      path: '/student-record/$id'
      fullPath: '/admin/student-record/$id'
      preLoaderRoute: typeof AdminStudentRecordIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCorrelativesRoute: typeof AdminCorrelativesRoute
  AdminEnrollmentsRoute: typeof AdminEnrollmentsRoute
  AdminFinalExamsRoute: typeof AdminFinalExamsRoute
  AdminGradesRoute: typeof AdminGradesRoute
  AdminProfessorsRoute: typeof AdminProfessorsRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminSubjectsRoute: typeof AdminSubjectsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminStudentRecordIdRoute: typeof AdminStudentRecordIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCorrelativesRoute: AdminCorrelativesRoute,
  AdminEnrollmentsRoute: AdminEnrollmentsRoute,
  AdminFinalExamsRoute: AdminFinalExamsRoute,
  AdminGradesRoute: AdminGradesRoute,
  AdminProfessorsRoute: AdminProfessorsRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminSubjectsRoute: AdminSubjectsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminStudentRecordIdRoute: AdminStudentRecordIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardAnnouncementsRoute: typeof DashboardAnnouncementsRoute
  DashboardCertificatesRoute: typeof DashboardCertificatesRoute
  DashboardExamsRoute: typeof DashboardExamsRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSubjectsRoute: typeof DashboardSubjectsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnnouncementsRoute: DashboardAnnouncementsRoute,
  DashboardCertificatesRoute: DashboardCertificatesRoute,
  DashboardExamsRoute: DashboardExamsRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSubjectsRoute: DashboardSubjectsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
